#pragma once

#define ATTRIBUTES 6
#define TARGET 1
#define N_COLS ATTRIBUTES + TARGET
#define TRAINING_PERCENT 80
#define TESTING_PERCENT 100 - TRAINING_PERCENT
#define TRAINING_SPLIT_RATIO TRAINING_PERCENT / 100.0

enum class Fields
{
  BUYING,
  MAINT,
  DOORS,
  PERSONS,
  LUG_BOOT,
  SAFETY,
  CLASS
};